# Generated by Django 4.2.2 on 2023-06-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='condition_food',
            new_name='food_name',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='info_food',
        ),
    ]
